---
version: 3

tasks:
  default:
    desc: <-- You are here
    cmds:
      - task --list-all

  init:
    cmds:
      - go mod init || echo "go.mod already exists"
      - go mod tidy

  run:
    cmds:
      - go mod tidy
      - go vet
      - go run main.go run alpine:latest

  build:
    cmds:
      - go build -ldflags "-X qd/cmd.Version=$(cat VERSION)" -o=bin/qd .
      - cp bin/qd $HOME/bin

  checks:
    deps: [test]
    cmds:
      - go mod tidy
      - go mod verify
      - go fmt
      - go vet
      - go clean

  local-release:
    deps: [test]
    cmds:
      - goreleaser release --snapshot --clean

  local-build:
    deps: [test]
    cmds:
      - goreleaser build --snapshot --clean

  release:
    deps: [checks, local-build]
    cmds:
      - goreleaser release --clean

  tag:
    cmds:
      - git tag -a v$(cat VERSION) -m "Release v$(cat VERSION)"
      - git push origin v$(cat VERSION)

  test:
    deps: [build]
    cmds:
      - go test ./...
      - ./tests/integration_test.sh bin/qd
