---
version: 3

tasks:
  init:
    cmds:
      - go mod init || echo "go.mod already exists"
      - go mod tidy
  
  run:
    cmds:
      - go mod tidy
      - go vet
      - go run main.go run alpine:latest
  
  build:
    cmds:
      - go mod tidy
      - go mod verify
      - go fmt
      - go vet
      - go clean
      - go build -ldflags "-X qd/cmd.Version=$(cat VERSION)" -o=bin/qd .
      - cp bin/qd $HOME/bin
