name: Lint and run checks

on:
  push:
    branches:
      - '**'

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: Install taskfile
      run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run task checks
      run: task checks
