name: Tests

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Install expect
        run: sudo apt-get install -y expect

      - name: Install Taskfile
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Run checks
        run: task checks
