name: Tests

on:
  push:
    branches:
      - '**'

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Install expect on Ubuntu
        run: sudo apt-get install -y expect

      - name: Install taskfile
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run task tests and checks
        run: task checks
