name: Bump Version and Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Read current version
        id: current
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Bump version (patch)
        id: bumped
        run: |
          ver=$(cat VERSION)
          IFS='.' read -r major minor patch <<< "$ver"
          patch=$((patch + 1))
          new_version="$major.$minor.$patch"
          echo "$new_version" > VERSION
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Commit and push new version
        run: |
          git add VERSION
          git commit -m "chore: bump version to ${{ steps.bumped.outputs.new_version }}"
          git tag -a "v${{ steps.bumped.outputs.new_version }}" -m "Release v${{ steps.bumped.outputs.new_version }}"
          git push origin main
          git push origin "v${{ steps.bumped.outputs.new_version }}"
